import { SPENDING_LIMIT_RESET_FREQUENCY } from "@b2b/types/constants"
import type { MedusaRequest, MedusaResponse } from "@medusajs/framework"

export const GET = async (_req: MedusaRequest, res: MedusaResponse) => {
  const response = {
    columns: [
      {
        id: "logo_url",
        field: "logo_url",
        name: "Logo",
        data_type: "string",
        render_mode: "image",
        sortable: false,
        hideable: true,
        default_visible: true,
        default_order: 10,
        filter: { enabled: false },
      },
      {
        id: "name",
        field: "name",
        name: "Name",
        data_type: "string",
        render_mode: "text",
        sortable: true,
        hideable: false,
        default_visible: true,
        default_order: 20,
        filter: { enabled: false },
      },
      {
        id: "phone",
        field: "phone",
        name: "Phone",
        data_type: "string",
        render_mode: "phone",
        sortable: false,
        hideable: true,
        default_visible: true,
        default_order: 30,
        filter: { enabled: false },
      },
      {
        id: "email",
        field: "email",
        name: "Email",
        data_type: "string",
        render_mode: "email",
        sortable: false,
        hideable: true,
        default_visible: true,
        default_order: 40,
        filter: { enabled: false },
      },
      {
        id: "address",
        field: "address",
        name: "Address",
        data_type: "string",
        render_mode: "b2b-company-address",
        sortable: false,
        hideable: true,
        default_visible: true,
        default_order: 50,
        filter: { enabled: false },
      },
      {
        id: "country",
        field: "country",
        name: "Country",
        data_type: "string",
        render_mode: "b2b-company-country",
        sortable: true,
        hideable: true,
        default_visible: true,
        default_order: 55,
        filter: { enabled: true },
      },
      {
        id: "currency_code",
        field: "currency_code",
        name: "Currency",
        data_type: "string",
        render_mode: "b2b-company-currency",
        sortable: true,
        hideable: true,
        default_visible: true,
        default_order: 58,
        filter: { enabled: true },
      },
      {
        id: "employees",
        field: "employees_count",
        name: "Employees",
        data_type: "number",
        render_mode: "b2b-employees-count",
        sortable: true,
        hideable: true,
        default_visible: true,
        default_order: 60,
        filter: { enabled: true },
      },
      {
        id: "customer_group",
        field: "customer_group",
        name: "Customer Group",
        data_type: "string",
        render_mode: "b2b-company-customer-group",
        sortable: true,
        hideable: true,
        default_visible: true,
        default_order: 70,
        filter: { enabled: true },
      },
      {
        id: "spending_limit_reset_frequency",
        field: "spending_limit_reset_frequency",
        name: "Reset Frequency",
        data_type: "enum",
        render_mode: "text",
        sortable: true,
        hideable: true,
        default_visible: true,
        default_order: 80,
        filter: {
          enabled: true,
          enumValues: SPENDING_LIMIT_RESET_FREQUENCY,
        },
      },
      {
        id: "created_at",
        field: "created_at",
        name: "Created At",
        data_type: "date",
        render_mode: "date",
        sortable: true,
        hideable: true,
        default_visible: true,
        default_order: 90,
        filter: { enabled: true },
      },
    ],
  }

  return res.json(response)
}
