import { QUOTE_STATUS } from "@b2b/types/constants"
import type { MedusaRequest, MedusaResponse } from "@medusajs/framework"

export const GET = async (_req: MedusaRequest, res: MedusaResponse) => {
  const response = {
    columns: [
      {
        id: "status",
        field: "status",
        name: "Status",
        data_type: "enum",
        render_mode: "b2b-quote-status",
        sortable: false,
        hideable: false,
        default_visible: true,
        default_order: 10,
        filter: {
          enabled: true,
          enumValues: QUOTE_STATUS,
        },
      },
      {
        id: "customer",
        field: "customer",
        name: "Customer",
        data_type: "string",
        render_mode: "b2b-quote-customer-link",
        sortable: false,
        hideable: true,
        default_visible: true,
        default_order: 20,
        filter: { enabled: true },
      },
      {
        id: "draft_order_id",
        field: "draft_order_id",
        name: "Draft Order",
        data_type: "string",
        render_mode: "b2b-quote-draft-order-link",
        sortable: false,
        hideable: true,
        default_visible: true,
        default_order: 30,
        filter: { enabled: true },
      },
      {
        id: "order_change_id",
        field: "order_change_id",
        name: "Order Change",
        data_type: "string",
        render_mode: "b2b-quote-order-change-link",
        sortable: false,
        hideable: true,
        default_visible: true,
        default_order: 40,
        filter: { enabled: false },
      },
      {
        id: "cart_id",
        field: "cart_id",
        name: "Cart",
        data_type: "string",
        render_mode: "b2b-quote-cart-link",
        sortable: false,
        hideable: true,
        default_visible: true,
        default_order: 50,
        filter: { enabled: true },
      },
      {
        id: "messages_count",
        field: "messages_count",
        name: "Messages",
        data_type: "number",
        render_mode: "text",
        sortable: false,
        hideable: true,
        default_visible: true,
        default_order: 60,
        filter: { enabled: false },
      },
      {
        id: "created_at",
        field: "created_at",
        name: "Created At",
        data_type: "date",
        render_mode: "date",
        sortable: true,
        hideable: true,
        default_visible: true,
        default_order: 70,
        filter: { enabled: false },
      },
    ],
  }

  return res.json(response)
}
